export const SET_CURRENT_DATA = 'SET_CURRENT_DATA';
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_BACKGROUND = 'SET_BACKGROUND';
export const SET_BACKDROP = 'SET_BACKDROP';